# Generated by Django 3.2.7 on 2021-10-16 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_alter_awards_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.achievements'),
        ),
        migrations.AlterField(
            model_name='player',
            name='achievements',
            field=models.ManyToManyField(blank=True, null=True, related_name='achievement', through='statistic.Awards', to='statistic.Achievements'),
        ),
    ]
