# Generated by Django 3.2.7 on 2021-10-16 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0004_alter_player_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game1',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='statistic.player'),
        ),
    ]
