# Generated by Django 3.2.7 on 2021-10-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0006_alter_game1_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
