# Generated by Django 3.2.7 on 2021-10-17 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0008_alter_game1_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagestat',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avg_stats', to='statistic.player'),
        ),
        migrations.AlterField(
            model_name='game1',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats1', to='statistic.player'),
        ),
        migrations.AlterField(
            model_name='game2',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats2', to='statistic.player'),
        ),
    ]
