# Generated by Django 3.2.7 on 2021-10-17 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0009_auto_20211017_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField()),
                ('pts', models.IntegerField()),
                ('fgm2', models.IntegerField()),
                ('fga2', models.IntegerField()),
                ('fg2', models.IntegerField()),
                ('fgm3', models.IntegerField()),
                ('fga3', models.IntegerField()),
                ('fg3', models.IntegerField()),
                ('fgm', models.IntegerField()),
                ('fga', models.IntegerField()),
                ('fg', models.IntegerField()),
                ('ftm', models.IntegerField()),
                ('fta', models.IntegerField()),
                ('ft', models.IntegerField()),
                ('oreb', models.IntegerField()),
                ('dreb', models.IntegerField()),
                ('reb', models.IntegerField()),
                ('ast', models.IntegerField()),
                ('tov', models.IntegerField()),
                ('stl', models.IntegerField()),
                ('blk', models.IntegerField()),
                ('eff', models.IntegerField()),
                ('plus_minus', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats3', to='statistic.player')),
            ],
        ),
    ]
