# Generated by Django 3.2.7 on 2021-10-24 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0011_auto_20211020_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagestat',
            name='ast',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='blk',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='dreb',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='eff',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='fg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='fg2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='fg3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='fga',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='fga2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='fga3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='fgm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='fgm2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='fgm3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='ft',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='fta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='ftm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='min',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='oreb',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='plus_minus',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='pts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='reb',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='stl',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='averagestat',
            name='tov',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='statistic.team'),
        ),
    ]
