# Generated by Django 3.2.7 on 2021-10-24 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0012_auto_20211024_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='year_awarded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='statistic.team'),
        ),
    ]
