# Generated by Django 3.2.7 on 2021-10-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0014_auto_20211030_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagestat',
            name='min',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game1',
            name='min',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game2',
            name='min',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='game3',
            name='min',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
