# Generated by Django 3.2.7 on 2021-10-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0018_player_rus_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rus_name',
        ),
        migrations.AddField(
            model_name='player',
            name='rus_first_name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='rus_last_name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='losses',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
