# Generated by Django 3.2.7 on 2021-10-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0019_auto_20211031_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='injured',
            field=models.BooleanField(default=False),
        ),
    ]
