# Generated by Django 3.2.7 on 2021-10-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0020_player_injured'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_logo/%Y/%m/%d/', verbose_name='фото'),
        ),
    ]
