# Generated by Django 3.2.7 on 2021-11-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0022_auto_20211106_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.TextField(blank=True, null=True),
        ),
    ]
