# Generated by Django 3.2.7 on 2021-12-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0024_auto_20211128_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files_2_upload')),
            ],
        ),
    ]
